name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Setup key
      - run: set -eu
      - run: mkdir "$HOME/.ssh"
      - run: echo "${{ secrets.keyasdf }}" > "$HOME/.ssh/test17"
      - run: chmod 600 "$HOME/.ssh/test17"
      # Deploy
      - run: rsync -e "ssh -i $HOME/.ssh/test17 -o StrictHostKeyChecking=no" --archive --compress --delete . 104.248.244.28:/var/reserv/site
