name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Setup key
      - run: set -eu
      - run: mkdir "$HOME/.ssh"
      - run: echo "${{ secrets.key }}" > "$HOME/.ssh/test17"
      - run: chmod 600 "$HOME/.ssh/test17"
      # Deploy
      - run: cd app && rsync -e "ssh -p 20022 -i $HOME/.ssh/test -o StrictHostKeyChecking=no" --archive --compress --delete . m71516@hostru04.fornex.org:/home/m71516/public_html/wp.maxgraph.ru
